/**
 * WARNING: This file was auto-generated by svgr. Do not edit.
 */
import * as React from 'react';
import type { SVGProps } from 'react';
/**
 * @internal
 */
declare const SvgQualityPoorIcon: (props: SVGProps<SVGSVGElement>) => React.JSX.Element;
export default SvgQualityPoorIcon;
//# sourceMappingURL=QualityPoorIcon.d.ts.map