[phases.install]
dependsOn = ['setup']
cmds = [
  'sudo apt-get update',
  'sudo apt-get install -y wget unzip',
  'wget https://github.com/protocolbuffers/protobuf/releases/download/v25.1/protoc-25.1-linux-x86_64.zip',
  'sudo unzip -o protoc-25.1-linux-x86_64.zip -d /usr/local bin/protoc',
  'sudo unzip -o protoc-25.1-linux-x86_64.zip -d /usr/local "include/*"',
  'rm -f protoc-25.1-linux-x86_64.zip',
  'protoc --version'
]

[phases.build]
dependsOn = ['install'] 